# Generated by Django 4.2.24 on 2025-09-15 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ifrs17submission',
            name='file_type',
            field=models.CharField(blank=True, choices=[('csv', 'CSV'), ('xlsx', 'Excel'), ('xbrl', 'XBRL')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ifrs17submission',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='ifrs17_submissions/%Y/%m/'),
        ),
    ]
