# Generated by Django 4.2.24 on 2025-09-17 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_reinsuranceheld_insurancerevenue_ifrs4transition_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ifrs17submission',
            unique_together=set(),
        ),
    ]
